version: '3'
services:
      dbos:
        image: mysql:5.7
        volumes:
             - mysql_storage:/var/lib/mysql
        restart: always
        environment:
             MYSQL_ROOT_PASSWORD: rootpass
             MYSQL_USER: karan
             MYSQL_PASSWORD: dewani
             MYSQL_DATABASE: drupaldb
      drupalos:
         image: drupal:latest
         volumes: 
             - drupal-modules:/var/www/html/modules
             - drupal-profile:/var/www/html/profile
             - drupal-sites:/var/www/html/sites
             - drupal-themes:/var/www/html/themes
         ports:
             - 8082:80
         restart: always

volumes:
        drupal-modules:
        drupal-profile:
        drupal-sites:
        drupal-themes:
        mysql_storage:

